apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magic-volcanoes-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.appHostname }}"
spec:
  tls:
    - hosts:
        - "{{ .Values.appHostname }}"
      secretName: volcanoes-tls
  rules:
    - host: "{{ .Values.appHostname }}"
      http:
        paths:
          - backend:
              service:
                name: magic-volcanoes-service
                port:
                  number: 80
            path: /
            pathType: Prefix